name: Preprocessing Workflow

on:
  push:
    paths:
      - 'namadataset_raw/**'
      - 'preprocessing/automate_*.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas scikit-learn

    - name: Run preprocessing script
      run: python preprocessing/automate_Muhammad-Fariz-Ramadhan.py

    - name: Upload processed data
      uses: actions/upload-artifact@v3
      with:
        name: processed-dataset
        path: preprocessing/Customer-Churn/processed.csv
